# Generated by Django 4.1.2 on 2022-10-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_user_account_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Account',
            new_name='Bank_Account',
        ),
    ]
